
image: drud/ddev-gitpod-base:20221018

tasks:
  - name: ddev-gitpod-launcher
    before: |
      {
      export TASK="before";
      bash .gitpod.sh
      }
    init: |
      {
      export TASK="init";
      bash .gitpod.sh 
      }
    command: |
      ddev launch

